import os
from text_to_speech import save

texts = [ ]
texts.append("Welcome")
texts.append("1 pulse 1st version")
texts.append("2 pulse 1st version")
texts.append("3 pulse 1st version")
texts.append("4 pulse 1st version")
texts.append("5 pulse 1st version")
texts.append("6 pulse 1st version")
texts.append("7 pulse 1st version")
texts.append("8 pulse 1st version")
texts.append("9 pulse 1st version")
texts.append("Welcome")
texts.append("1 pulse 2nd version")
texts.append("2 pulse 2nd version")
texts.append("3 pulse 2nd version")
texts.append("4 pulse 2nd version")
texts.append("5 pulse 2nd version")
texts.append("6 pulse 2nd version")
texts.append(".")
texts.append("-")
texts.append(".")
texts.append("Welcome")
texts.append("1 pulse 3rd version")
texts.append("2 pulse 3rd version")
texts.append("3 pulse 3td version")
texts.append("4 pulse 3rd version")
texts.append("5 pulse 3rd version")
texts.append("6 pulse 3rd version")
texts.append(".")
texts.append(".")
texts.append(".")
texts.append("Welcome")
texts.append("1 pulse 4th version")
texts.append("2 pulse 4th version")
texts.append("3 pulse 4th version")
texts.append("4 pulse 4th version")
texts.append("5 pulse 4th version")
texts.append("6 pulse 4th version")
texts.append(".")
texts.append(".")
texts.append(".")
texts.append("Welcome")
texts.append("1 pulse 5th version")
texts.append("2 pulse 5th version")
texts.append("3 pulse 5th version")
texts.append("4 pulse 5th version")
texts.append("5 pulse 5th version")
texts.append("6 pulse 5th version")
texts.append(".")
texts.append(".")
texts.append(".")
texts.append("Welcome")

for text in texts:
    print("----")
    print(text)
    print("++++")
